name: Workflow to run lint
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  ci-pipeline:
    name: Ci flow
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@master
      - name: Checkout
        uses: actions/checkout@v2
        with:
          python-version: 3.6
      - name: Install flake8
        run: python3.6 -m pip install black flake8 --upgrade pip

      - name: Run linters
        uses: wearerequired/lint-action@v1
        with:
          black: true
          flake8: true