name: Workflow to run lint
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  ci-pipeline:
    name: Ci flow
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@master
      - name: Checkout
        uses: actions/checkout@v2
        with:
          python-version: 3.7
      - name: Install flake8
        run: python -m pip install --upgrade pip
             pip install flake8 black

      - name: Run linters
        uses: wearerequired/lint-action@v1
        with:
          black: true
          flake8: true